### PR TITLE
chore(loggly): switch to mainted, offical loggly fork

### LINKED ISSUE #635: use official loggly fork node-loggly-bulk
https://github.com/loggly/node-loggly-bulk

### PR DESCRIPTION
**Pull request by graingert**
Fixes #635

### CODE REVIEW

**Comment by nomiddlename** [comment]
Thanks for this. Does the new lib implement exactly the same API? No code changes needed for it to work?

**Comment by graingert** [comment]
Docs seem about the same

**Comment by nomiddlename** [comment]
You've tested this change against a real loggly implementation? I don't use loggly, so I'll have to take your word for it.

**Comment by graingert** [comment]
Might be worth calling loggly support and getting them to comment here any problems they think might happen

**Comment by nomiddlename** [comment]
I'm closing this one. The loggly appender has been moved to https://github.com/log4js-node/loggly and is using the new library.

**Pull request closed without merging**
