### PR TITLE
fix: #793

### PR DESCRIPTION
**Pull request by so5**

### CODE REVIEW

**Comment by nomiddlename** [comment]
Thanks for this, good catch - could you add a test that covers the change, please? That way I can be sure it won't be broken again by any future changes.

**Comment by so5** [comment]
Hi, I add a test case which will call shutdown before use.

**Comment by nomiddlename** [comment]
Thanks again, I appreciate the help.

**Comment by nomiddlename** [comment]
Published to npm in log4js@3.0.6

**Pull request merged**
