### PR TITLE
fix: Allow appenders to depend on not-yet-loaded appenders.

### LINKED ISSUE #746: TypeError: appender is not a function
The order in which the appenders are defined seems _very_ important. This gives some strange results:

This sample:

```ts
const log4js = require('log4js');
log4js.configure({
  appenders: {
     filteredConsole: { type: 'logLevelFilter', appender: 'console', level: 'info' },
     console: { type: 'stdout' }
  },
  categories: {
    default: { appenders: ['filteredConsole'], level: 'trace' }
  }
});
log4js.getLogger('demo').info('test');
```

Results in error: `TypeError: appender is not a function`. 

A solution would be to sort the appenders topologically. We could use something like [toposort](https://www.npmjs.com/package/toposort)

### PR DESCRIPTION
**Pull request by mvastola**
Close #746

### CODE REVIEW

**Comment by mvastola** [comment]
@nomiddlename test is added (and passing).

**Comment by mvastola** [comment]
Actually, just spotted a bug. Give me a min.

**Comment by mvastola** [comment]
Ok. Now it should be good.

**Comment by nomiddlename** [comment]
Thanks for this - published to NPM in  log4js@6.1.2

**Comment by mvastola** [comment]
@nomiddlename Thanks!!

**Pull request merged**
