### PR TITLE
docs: add explaining custom format

### PR DESCRIPTION
**Pull request by Simmyoungsub**
@nomiddlename 
I add something to the docs explaining how to add the body token to a custom format. related to #868

### CODE REVIEW

**Comment by Simmyoungsub** [comment]
May i add test case in connect-logger-test.js if this commit have merged?

**Comment by nomiddlename** [comment]
Put the code change, the test and the documentation change all in this pull request together.

**Comment by Simmyoungsub** [comment]
Thanks for your reply!
I updated it
Please confirm my commit
Thank you!

**Comment by nomiddlename** [comment]
This is good, thanks. I thought your original pull request was going to add support for `:body` as a token, but this is better - no extra log4js code needed.

**Comment by Simmyoungsub** [comment]
I'm glad to be of your help. Thank you!

**Pull request merged**
