### PR TITLE
Add line + column number to each log line

### PR DESCRIPTION
**Pull request by dhruvbird**
I think log lines should contain a line + column number so that debugging issues becomes easier. You no longer need to identify a log line with some sort of unique identifier if line numbers are present.

### CODE REVIEW

**Comment by leegee** [comment]
This would be a really useful feature, on way or another. 
I don't mind it slowing-down my code when it is turned on, because it will only be turned on for either debugging or errors, and debuggin code is never deployed to production, and errors are (hopefully) rare.
Would it be possible to have a flag set when the conversion pattern is parsed, and then only gather and parse the Error.stack information if that flag has been set?

**Comment by nomiddlename** [comment]
The stack trace has to be generated when the logging event is created - you'll get strange problems if you generate it in the layout used by the appender. My problem has always been working out how to add this expensive feature in without slowing things down for everyone (while still producing useful traces). Perhaps a good way of doing it would be to use the NODE_DEBUG environment variable to trigger generating traces in the logger?

**Comment by leegee** [comment]
Why can't you use the Log4js configuration to turn it off/on, set a boolean if %l (etc) is found in the pattern layout when it is first met..?

**Comment by ihmabreu** [comment]
You can always use the [log4js-extend](https://github.com/ww24/log4js-node-extend) while this important feature is not part of log4js.

**Comment by nomiddlename** [comment]
Closing this one - it has been replaced by #580

**Pull request closed without merging**
