### PR TITLE
Configure method for oneliners

### PR DESCRIPTION
**Pull request by idenisovs**
The changes within this PR allow to write code like:
```javascript
const log = require('log4js').configure(conf).getLogger('daemon');
```

For this PR I have:

1. Added `return` statement for log4js.configure(...) method.
2. Refactored the `configuration-test.js` file.
3. Added new test to `configuration-test.js` file. This test checks  the value, returned by `log4js.configure(...)` method.
4. Appended the `configure(...)` related article in the docs.

### CODE REVIEW

**Comment by nomiddlename** [comment]
Thanks for this - only one small thing left to do, which is update the typescript definition (it's in `types/log4js.d.ts`) to include the return value.

**Comment by idenisovs** [comment]
@nomiddlename Sorry for asking this (I have no experience with TypeScript), but will be type `object` the proper solution for this?

Like 

```typescript
export function configure(filename: string): object;
export function configure(config: Configuration): object;
```

**Comment by nomiddlename** [comment]
I have no idea either - all I know is that the TypeScript people are pretty quick off the mark if we get it wrong :) - but I think you want to use `this` instead of `object` in your example above, to show it is returning a log4js class (sort of). A good way to test it is to add your one-liner code to the test.ts file in the types directory and see if it compiles with typescript.

**Comment by idenisovs** [comment]
Usage of `this` produces the following errors:

```
$ tsc test.ts
log4js.d.ts(5,46): error TS2526: A 'this' type is available only in a non-static member of a class or interface.
log4js.d.ts(6,51): error TS2526: A 'this' type is available only in a non-static member of a class or interface.
```
Seems, that with current implementation of `test.ts` file, there is only two solutions:

1. Redefine internal interface `Log4js`, which will have copy of exported functions itself (so it will be declared here twice).
2. Set return type of `configure(...)` methods to `any`.

At the moment, first seems the better, so I'll put it in the definition file, and will hope, that later someone, more experienced with Typescript, will put here the better solution.

**Comment by nomiddlename** [comment]
Hey typescript experts (or at least people who have contributed changes to the typescript definitions): @xialeistudio @pe8ter @hansonw @taoqf @AmShaegar13  - could you offer some guidance to @idenisovs please? I'm out of my depth here.

**Comment by AmShaegar13** [comment]
How about this:

```
diff --git types/log4js.d.ts types/log4js.d.ts
index 01c48eb..f6822ec 100644
--- types/log4js.d.ts
+++ types/log4js.d.ts
@@ -2,8 +2,8 @@
 
 export function getLogger(category?: string): Logger;
 
-export function configure(filename: string): void;
-export function configure(config: Configuration): void;
+export function configure(filename: string): Log4js;
+export function configure(config: Configuration): Log4js;
 
 export function addLayout(name: string, config: (a: any) => (logEvent: LoggingEvent) => string): void;
 
@@ -13,6 +13,15 @@ export function levels(): Levels;
 
 export function shutdown(cb?: (error: Error) => void): void | null;
 
+export interface Log4js {
+	getLogger;
+	configure;
+	shutdown;
+	connectLogger;
+	levels;
+	addLayout;
+}
+
 export interface BaseLayout {
 	type: 'basic';
 }
diff --git types/test.ts types/test.ts
index 91e1b84..e8159a6 100644
--- types/test.ts
+++ types/test.ts
@@ -1,6 +1,6 @@
 import * as log4js from './log4js';
 
-log4js.configure('./filename');
+log4js.configure('./filename').getLogger();
 const logger1 = log4js.getLogger();
 logger1.level = 'debug';
 logger1.debug("Some debug messages");
```

**Comment by idenisovs** [comment]
@AmShaegar13 I spent couple of hours, trying to figure out, how to do something like this. Nevermind, that it could be so easy. 😆 
Thank you!

**Comment by nomiddlename** [comment]
Thanks for this @idenisovs, and thanks to @AmShaegar13 for helping out. This will go out to NPM in version 2.6.x, I'd like to bundle up deprecating a few of the appenders first in preparation for removing them in version 3.x.

**Pull request merged**
