### PR TITLE
fix: Logger has not export in entry file

### LINKED ISSUE #1275: Class Logger has not been export from entry file
```
Version: 6.5.2
```

[`lib/log4js.js`](https://github.com/log4js-node/log4js-node/blob/3582a00747b08e4afedbd52308e48b590d4c7b29/lib/log4js.js#L163): 
```js
const log4js = {
  getLogger,
  configure,
  shutdown,
  connectLogger,
  levels,
  addLayout: layouts.addLayout,
  recording,
};

module.exports = log4js;
```

[`types/log4js.d.ts`](https://github.com/log4js-node/log4js-node/blob/3582a00747b08e4afedbd52308e48b590d4c7b29/types/log4js.d.ts#L405):
```typescript
export class Logger {
  ...
}
```

### PR DESCRIPTION
**Pull request by taozi0818**
Fix #1275

### CODE REVIEW

**Comment by lamweili** [comment]
### History in 2.0.0
It was changed from `interface` to `class` back in a1e40c229eef1cf9b9986bd08a9d9f2e71af2213 which was released as `2.9.0`.
It was probably due to the exposure of `Logger` as a global variable.
https://github.com/log4js-node/log4js-node/blob/a1e40c229eef1cf9b9986bd08a9d9f2e71af2213/lib/log4js.js#L208
https://github.com/log4js-node/log4js-node/blob/a1e40c229eef1cf9b9986bd08a9d9f2e71af2213/lib/logger.js#L134-L137

### Refactored in 3.0.0
The global variable `Logger` has since been removed in 8084e80027dcfa290fc92dd4df85f935807106e4 which was released as `3.0.0`.
But there was no change to the typings `log4js.d.ts`.

**Thus, would a single line change,  `class` to `interface`, be better?**

**Comment by lamweili** [comment]
### History in 2.0.0
It was changed from `interface` to `class` back in a1e40c229eef1cf9b9986bd08a9d9f2e71af2213 which was released as `2.9.0`.
It was probably due to the exposure of `Logger` as a global variable.
https://github.com/log4js-node/log4js-node/blob/a1e40c229eef1cf9b9986bd08a9d9f2e71af2213/lib/log4js.js#L208
https://github.com/log4js-node/log4js-node/blob/a1e40c229eef1cf9b9986bd08a9d9f2e71af2213/lib/logger.js#L134-L137

### Refactored in 3.0.0
The global variable `Logger` has since been removed in 8084e80027dcfa290fc92dd4df85f935807106e4 which was released as `3.0.0`.
But there was no change to the typings `log4js.d.ts`.

---

**Thus, would a single line change from `class` to `interface` in `log4js.d.ts` (a reversal of a1e40c229eef1cf9b9986bd08a9d9f2e71af2213), be better?**

https://github.com/log4js-node/log4js-node/blob/3582a00747b08e4afedbd52308e48b590d4c7b29/types/log4js.d.ts#L405

```diff
-        export class Logger { 
+        export interface Logger { 
```

Because `Logger` should not be used standalone. It is wrapped around and should only be retrieved from `getLogger()`.
https://github.com/log4js-node/log4js-node/blob/3582a00747b08e4afedbd52308e48b590d4c7b29/lib/log4js.js#L144-L154

**Review by lamweili — CHANGES_REQUESTED** [review]
### History in 2.0.0
It was changed from `interface` to `class` back in a1e40c229eef1cf9b9986bd08a9d9f2e71af2213 which was released as `2.9.0`.
It was probably due to the exposure of `Logger` as a global variable on `configure()`.
https://github.com/log4js-node/log4js-node/blob/a1e40c229eef1cf9b9986bd08a9d9f2e71af2213/lib/log4js.js#L208
https://github.com/log4js-node/log4js-node/blob/a1e40c229eef1cf9b9986bd08a9d9f2e71af2213/lib/logger.js#L134-L137

### Refactored in 3.0.0
The global variable `Logger` has since been removed in 8084e80027dcfa290fc92dd4df85f935807106e4 which was released as `3.0.0`.
But there was no change to the typings `log4js.d.ts`.

---

**Thus, would a single line change from `class` to `interface` in `log4js.d.ts` (a reversal of a1e40c229eef1cf9b9986bd08a9d9f2e71af2213) be better?**

https://github.com/log4js-node/log4js-node/blob/3582a00747b08e4afedbd52308e48b590d4c7b29/types/log4js.d.ts#L405

```diff
-        export class Logger { 
+        export interface Logger { 
```

Because `Logger` should not be used standalone. It should only get retrieved from `getLogger()`.
https://github.com/log4js-node/log4js-node/blob/3582a00747b08e4afedbd52308e48b590d4c7b29/lib/log4js.js#L144-L156

**Comment by taozi0818** [comment]
OK. Both methods are available. The key point is keeping them consistent.

**Comment by lamweili** [comment]
@taozi0818 Thanks! I rebased.

**Review by lamweili — APPROVED** [review]

**Pull request merged**
